"""Constants for LockLearn."""

DOMAIN = "locklearn"
INTEGRATION_VERSION = "1.0.0-beta.1"
FRONTEND_PROTOCOL_VERSION = 3
CONFIG_ENTRY_VERSION = 1
DB_SCHEMA_VERSION = 5
CONTENT_SCHEMA_VERSION = 2
SUPPORTED_CONTENT_SCHEMA_VERSIONS = frozenset({1, CONTENT_SCHEMA_VERSION})

DATA_RUNTIME = "runtime"
DATA_STATIC_REGISTERED = "static_registered"
PANEL_URL_PATH = "locklearn"
PANEL_COMPONENT_NAME = "locklearn-panel"
STATIC_URL_PATH = "/locklearn_static"

CONF_CREATE_PERSONAL_PROFILE = "create_personal_profile"
CONF_UI_LANGUAGE = "ui_language"
CONF_UNINSTALL_DATA_POLICY = "uninstall_data_policy"
CONF_RESTORE_SNAPSHOT = "restore_snapshot"
CONF_PURGE_CONTENT_CACHE = "purge_content_cache"
DEFAULT_UI_LANGUAGE = "en"
SUPPORTED_UI_LANGUAGES = ("en", "fr")

DEFAULT_UNINSTALL_DATA_POLICY = "keep_user_data"
