"""Generate drift-sensitive documentation contracts from runtime sources."""

from __future__ import annotations

import argparse
import ast
import json
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "custom_components" / "locklearn" / "storage" / "schema.py"
WEBSOCKET_PATH = ROOT / "custom_components" / "locklearn" / "api" / "websocket.py"
CONST_PATH = ROOT / "custom_components" / "locklearn" / "const.py"
GENERATED = ROOT / "docs" / "generated"


def _string_constant(path: Path, name: str) -> str:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == name for target in node.targets
        ):
            value = ast.literal_eval(node.value)
            if isinstance(value, str):
                return value
    raise ValueError(f"{name} not found in {path}")


def _integer_constant(path: Path, name: str) -> int:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == name for target in node.targets
        ):
            value = ast.literal_eval(node.value)
            if isinstance(value, int):
                return value
    raise ValueError(f"{name} not found in {path}")


def _parse_schema(sql: str) -> dict[str, list[dict[str, Any]]]:
    tables: list[dict[str, Any]] = []
    table_pattern = re.compile(r"CREATE TABLE IF NOT EXISTS\s+([A-Za-z0-9_]+)\s*\(([\s\S]*?)\);")
    for match in table_pattern.finditer(sql):
        name = match.group(1)
        ddl = f"CREATE TABLE IF NOT EXISTS {name} ({match.group(2)});".strip()
        foreign_keys: list[dict[str, str]] = []
        for fk in re.finditer(
            r"([A-Za-z0-9_]+)[^,\n]*?\bREFERENCES\s+"
            r"([A-Za-z0-9_]+)\s*\(([^)]+)\)",
            ddl,
        ):
            foreign_keys.append(
                {
                    "from": fk.group(1),
                    "to_table": fk.group(2),
                    "to_columns": fk.group(3).strip(),
                }
            )
        for fk in re.finditer(
            r"FOREIGN KEY\s*\(([^)]+)\)\s*REFERENCES\s+"
            r"([A-Za-z0-9_]+)\s*\(([^)]+)\)",
            ddl,
        ):
            foreign_keys.append(
                {
                    "from": fk.group(1).strip(),
                    "to_table": fk.group(2),
                    "to_columns": fk.group(3).strip(),
                }
            )
        tables.append({"name": name, "ddl": ddl, "foreign_keys": foreign_keys})

    indexes: list[dict[str, str]] = []
    index_pattern = re.compile(
        r"CREATE INDEX IF NOT EXISTS\s+([A-Za-z0-9_]+)\s+ON\s+"
        r"([A-Za-z0-9_]+)\s*\(([\s\S]*?)\);"
    )
    for match in index_pattern.finditer(sql):
        indexes.append(
            {
                "name": match.group(1),
                "table": match.group(2),
                "columns": re.sub(r"\s+", " ", match.group(3)).strip(),
            }
        )
    return {"tables": tables, "indexes": indexes}


def _database_markdown(
    title: str,
    source_constant: str,
    parsed: dict[str, list[dict[str, Any]]],
) -> str:
    relationships: set[str] = set()
    for table in parsed["tables"]:
        for foreign_key in table["foreign_keys"]:
            relationships.add(f"    {foreign_key['to_table']} ||--o{{ {table['name']} : references")

    lines = [
        f"# {title}",
        "",
        "> Generated by `scripts/generate_docs_contracts.py`. Do not edit by hand.",
        (f"> Source: `custom_components/locklearn/storage/schema.py` / `{source_constant}`."),
        "",
        "## ER diagram",
        "",
        "```mermaid",
        "erDiagram",
    ]
    if relationships:
        lines.extend(sorted(relationships))
    else:
        lines.append("    %% No explicit foreign-key relationships found.")
    lines.extend(["```", "", "## Tables", ""])

    for table in parsed["tables"]:
        lines.extend(
            [
                f"### `{table['name']}`",
                "",
                "```sql",
                str(table["ddl"]),
                "```",
                "",
            ]
        )
        indexes = [index for index in parsed["indexes"] if index["table"] == table["name"]]
        if indexes:
            lines.extend(["Indexes:", ""])
            for index in indexes:
                lines.append(f"- `{index['name']}` on `{index['columns']}`")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _websocket_contracts(source: str, protocol_version: int) -> dict[str, Any]:
    starts = [
        match.start() for match in re.finditer(r"(?=@websocket_api\.websocket_command)", source)
    ]
    starts.append(len(source))
    commands: list[dict[str, Any]] = []
    for index, start in enumerate(starts[:-1]):
        block = source[start : starts[index + 1]]
        command_match = re.search(r'vol\.Required\("type"\):\s*"([^"]+)"', block)
        if command_match is None:
            continue
        command = command_match.group(1)
        handler_match = re.search(r"async def\s+([A-Za-z0-9_]+)", block)
        handler = "" if handler_match is None else handler_match.group(1)
        required = [
            item for item in re.findall(r'vol\.Required\("([^"]+)"\)', block) if item != "type"
        ]
        optional = re.findall(r'vol\.Optional\("([^"]+)"\)', block)

        access = "authenticated"
        if "_require_profile_permission(" in block:
            access = "profile-acl"
        elif "_require_track_permission(" in block:
            access = "track-via-profile-acl"
        elif "_authorized_session(" in block:
            access = "session-via-profile-acl"
        elif "_require_admin(" in block or "@websocket_api.require_admin" in block:
            access = "ha-admin"
        elif "_can_access_operation(" in block:
            access = "operation-owner-or-admin"
        elif command.startswith("locklearn/profiles/import_"):
            access = "owner-bound-upload-capability"

        commands.append(
            {
                "command": command,
                "handler": handler,
                "access": access,
                "required_request_fields": required,
                "optional_request_fields": optional,
                "response": (
                    "Home Assistant WebSocket result envelope; payload is handler-defined"
                ),
                "subscription": command.endswith("/subscribe"),
                "errors": sorted(set(re.findall(r"\b(ERR_[A-Z0-9_]+)\b", block))),
                "protocol_version": protocol_version,
            }
        )

    commands.sort(key=lambda item: str(item["command"]))
    return {"protocol_version": protocol_version, "commands": commands}


def _websocket_markdown(contract: dict[str, Any]) -> str:
    lines = [
        "# WebSocket contracts",
        "",
        "> Generated by `scripts/generate_docs_contracts.py`. Do not edit by hand.",
        "> Runtime source: `custom_components/locklearn/api/websocket.py`.",
        "",
        f"Frontend/backend protocol version: **{contract['protocol_version']}**.",
        "",
        (
            "Every command uses Home Assistant's authenticated WebSocket connection. "
            "The access column"
        ),
        ("describes the additional LockLearn authorization boundary enforced by the backend."),
        "",
        (
            "| Command | Handler | Access | Required request fields | "
            "Optional request fields | Errors |"
        ),
        "|---|---|---|---|---|---|",
    ]
    for command in contract["commands"]:
        required = ", ".join(f"`{item}`" for item in command["required_request_fields"]) or "—"
        optional = ", ".join(f"`{item}`" for item in command["optional_request_fields"]) or "—"
        errors = ", ".join(f"`{item}`" for item in command["errors"]) or "—"
        lines.append(
            f"| `{command['command']}` | `{command['handler']}` | "
            f"{command['access']} | {required} | {optional} | {errors} |"
        )

    lines.extend(
        [
            "",
            "## Response contract",
            "",
            (
                "All commands return the Home Assistant WebSocket result envelope. "
                "Nested result payloads are"
            ),
            (
                "versioned by `FRONTEND_PROTOCOL_VERSION` and implemented by the "
                "named handler; subscription"
            ),
            (
                "commands additionally emit server-pushed events after the initial "
                "successful result."
            ),
            "",
        ]
    )
    return "\n".join(lines)


def _outputs() -> dict[Path, str]:
    state = _parse_schema(_string_constant(SCHEMA_PATH, "STATE_SCHEMA"))
    content = _parse_schema(_string_constant(SCHEMA_PATH, "CONTENT_SCHEMA"))
    protocol = _integer_constant(CONST_PATH, "FRONTEND_PROTOCOL_VERSION")
    websocket = _websocket_contracts(
        WEBSOCKET_PATH.read_text(encoding="utf-8"),
        protocol,
    )
    return {
        GENERATED / "STATE_DB.md": _database_markdown(
            "state.db generated contract",
            "STATE_SCHEMA",
            state,
        ),
        GENERATED / "CONTENT_DB.md": _database_markdown(
            "content.db generated contract",
            "CONTENT_SCHEMA",
            content,
        ),
        GENERATED / "WEBSOCKET_CONTRACTS.md": _websocket_markdown(websocket),
        GENERATED / "websocket-contracts.json": (
            json.dumps(websocket, indent=2, sort_keys=True) + "\n"
        ),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    stale: list[str] = []
    for path, content in _outputs().items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    if stale:
        print("Generated documentation is stale:")
        for path in stale:
            print(f"- {path}")
        return 1

    if args.check:
        print("Generated documentation contracts: OK")
    else:
        print("Generated documentation contracts updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
